### ISSUE TITLE
Bad unit in zeus

### ISSUE THREAD

**Issue by Cuel** [fparma/fp_factions#2]
In Zeus, under OPFOR there's a faction called AAF
It has a single "Men" unit which is FP CH Type 07 Universal

Also gives this error

13:56:28 Warning Message: No entry 'bin\config.bin/CfgWeapons.FP_Jeitei'.
13:56:28 Warning Message: No entry '.scope'.
13:56:28 Warning Message: '/' is not a value
13:56:28 Warning Message: Error: creating weapon FP_Jeitei with scope=private

**Comment by CSLeader** [comment]
This issue was fixed in fp_uniforms' PLA update. Someone should close this one.
